install:
  - curl -fsSL get.docker.com -o get-docker.sh
  - sudo sh get-docker.sh

script:
  - sudo bash .travis.sh

deploy:
  provider: releases
  api_key:
    secure: vtoqL+KcnXeyAl7/Vbct8vRv0DYky/lX9Lxvj9hm5XuKoGuapdxaF/Ifi5iAXWcVKgkZFc0Z5PFuOmV7O63CpfjkOnobMh7Q+UaLDsF/xr7EjdzyOgGMnutwoTUPX1Mb9M8PLaHb92Vv2B96SMqsNdsKBtjlXxQw6svAkP5AThnOBySq2FU3BFGHxs/qq8dC32zQ2PuqknqD6pis+h14Z3Qx870psfz044dYm/ilEb+SDzSGY4e/6i4MDhVcR+/htbc3TLnmZxKl1nT4IXrO4c9WPt+WDa9a4c0pKF9l7SFnS+3Pb7bK17YKXTLmor5pJGxhT2fAcRTQ0dRNeYW+YKkC7AJPK78uQCqMxN6g/5ZioRo78Qbi4xoTC08hKkwLlmGtbFNYQ5iGGSj3cmkBTT74uo19zgshCYzYNXBzU1XhOlKrIXM1neK7LHqi9vVlmEwB3N25mP9gsNEZ31DipwVjnhslisMCjQInMgX94Z9s/S++pobKgsPv2ablA8MI4UPvLS+xzDC5QvJ7H2z3ccANfgrx6N1HygboiTfdZ0To5eEnw2ZYoj/Y37QOqC8bKHdEHgE6kbYjnctx9C3USkfcXLHFvijH0Sxyw9rYAiHU8mTOlMXTo1mxyDH1O7OKtR0/4P/2mUJb/JYWmcISAkIJsBW1X7TCntyjekZ7CMA=
  file_glob: true
  file: glibc-build/*-wml.tar.gz
  skip_cleanup: true
  on:
    condition: -a GLIBC_BUILD_DEPLOY.out
    repo: willmarkley/wml